### ISSUE TITLE
Memory issue for training Question generation

### ISSUE THREAD

**Issue by vapyc** [martiansideofthemoon/squash-generation#40]
```
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 259, in train
    torch.cuda.set_device(args.local_rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:33
```
@martiansideofthemoon I am only getting this issue when 

!python -m torch.distributed.launch --nproc_per_node=2 question-generation/train.py --eval_before_start --n_epochs 4 --model_checkpoint gpt2 --dataset_path data/temp_dataset/instances_corefs --dataset_cache data/temp_dataset/cache_corefs --output_dir question-generation/gpt2_corefs_question_generations

But when I remove 

!python question-generation/train.py --eval_before_start --n_epochs 4 --model_checkpoint gpt2 --dataset_path data/temp_dataset/instances_corefs --dataset_cache data/temp_dataset/cache_corefs --output_dir question-generation/gpt2_corefs_question_generations

Its gives memory issue. I don't know how to get around the issue.

**Comment by martiansideofthemoon** [comment]
Do you have two GPUs on your machine? `--nproc_per_node` indicates the number of GPUs being used. If you have lesser GPUs you might want to increase the accumulation.

**Comment by vapyc** [comment]
Well, I am currently using a single Kaggle GPU with 16gb capacity. So are u suggesting to --nproc_per_node =1 ? @martiansideofthemoon 
How could I increase the accumulation?

**Comment by martiansideofthemoon** [comment]
Yes, if you have a single GPU use `--nproc_per_node=1`. The repository has a `--gradient_accumulation_steps` flag that you can adjust, but it's already at 8 so maybe it's fine. Also since you have a P100 with 16GB, I recommend using GPT2-medium or GPT2-large. They are much better than GPT2-small :smile:

**Comment by vapyc** [comment]
Well, thanks for your input. It seems to work but it started to show this new error 
```
Traceback (most recent call last):
  File "question-generation/train.py", line 375, in <module>
    train()
  File "question-generation/train.py", line 359, in train
    checkpoint_handler = ModelCheckpoint(tb_logger.writer.log_dir, 'checkpoint', save_interval=1, n_saved=3)
AttributeError: 'SummaryWriter' object has no attribute 'log_dir'
```
@martiansideofthemoon  could you help me with this.I checked StackOverflow and github issues but couldn't find anything relevant?

**Comment by martiansideofthemoon** [comment]
I think this is a version issue, the flag name has slightly changed and there is a backward incompatibility. I've fixed this in the past using something like below, feel free to submit a PR to fix this.

```
try:
    tb_writer = SummaryWriter(logdir="runs/summary_%s" % args.job_id
except:
    tb_writer = SummaryWriter(log_dir="runs/summary_%s" % args.job_id)
```
